presets:
  Performance:
    description: Uses performance cores 16-31 (best for productivity)
    affinity: FFFF0000
    priority: null
  All:
    description: Uses all cores 0-31
    affinity: FFFFFFFF
    priority: null
  Cache:
    description: Uses cache cores 0-15 (best for gaming)
    affinity: FFFF
    priority: null
rules:
- on: !Path C:\Program Files\Steam\steamapps\common
  preset: Cache
  description: Matches all processes in the Steam common folder
- on: !Path D:\SteamLibrary\steamapps\common
  preset: Cache
  description: Matches all processes in an external Steam library
- on: !Path D:\Games
  preset: Cache
  description: Matches all processes in your games folder
default_preset: Performance
