default_profile: performance
profiles:
  cache:
    name: Cache
    description: Cache cores 0-15
    affinity_mask: 1
  performance:
    name: Performance
    description: Performance cores 16-31
    affinity_mask: 1
  all:
    name: All
    description: Performance cores 16-31
    affinity_mask: 1
    priority: 3
rules:
  - !PathRule
    path: D:\Games
    profile: cache
