import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { StandardTableView } from "std-widgets.slint";

export component ProcessTable inherits StandardTableView {
    columns: [
        { title: "PID", width: 60px },
        { title: "Name", width: 150px },
        { title: "Priority", width: 80px },
        { title: "Path", width: 350px },
    ];
}

export component AppWindow inherits Window {
    in-out property <[[StandardListViewItem]]> processes: [];
    in-out property <string> search <=> input.text;

    callback request-reload();
    callback search-change();

    VerticalBox {
        ProcessTable { rows: root.processes; }
        HorizontalBox {
            Text {
                max-width: 46px;
                text: "Search: ";
            }
            input := TextInput {
                edited => {
                    root.search-change();
                }
            }
        }
        Button {
            text: "Reload";
            clicked => {
                root.request-reload();
            }
        }
    }
}